### ISSUE TITLE
Suggestion: Upload to RStudio Cheatsheets Repository

### ISSUE THREAD

**Issue by jtelleriar** [roualdes/stan_cheatsheets#1]
We could upload the cheatsheet to the RStudio Cheatsheet repository :)

I could do the pull request if interested.

Juan

**Comment by roualdes** [comment]
Juan, go for it. Please see if they'll accept this in the RStudio Cheatsheet repository.

You reminded me to pay some attention to this repository, thanks.  I just touched up the cheatsheet a little bit.
